Fixup sched.h include
In file included from restart.c:34:
/opt/crosstool/gcc-4.2.4-glibc-2.3.6/i686-unknown-linux-gnu/lib/gcc/i686-unknown-linux-gnu/4.2.4/../../../../i686-unknown-linux-gnu/sys-include/linux/sched.h:109: error: redefinition of 'struct sched_param'

That include was added in 8fc8b640f8674d6de553cded539d24e08fac6f34
which added some pidns bits using CLONE_NEWPID. Looks like linux/sched.h
was included for this definition but it no longer seems necessary.

The same problem exists in test/ipcshm_multi.c

Signed-off-by: Matt Helsley <matthltc@us.ibm.com>