Fix missing CLONE_NEWIPC
Some not-so-old distros still lack the CLONE_NEWIPC definition:

cc -g -Wall -Wstrict-prototypes -Wno-trigraphs    ipcshm_multi.c  -lm -o ipcshm_multi
ipcshm_multi.c: In function ‘child3’:
ipcshm_multi.c:160: error: ‘CLONE_NEWIPC’ undeclared (first use in this function)
ipcshm_multi.c:160: error: (Each undeclared identifier is reported only once
ipcshm_multi.c:160: error: for each function it appears in.)
make[1]: *** [ipcshm_multi] Error 1
make[1]: Leaving directory `/tmp/user-cr/test'
make: *** [all] Error 2

Include the definition from "../clone.h"

Signed-off-by: Matt Helsley <matthltc@us.ibm.com>